parentregex = "^[a-z][-_a-z0-9]+$"
projectregex = "^[a-z][_a-z0-9]+$"
separator = "-"
joiner = "-"
groupid = "org.sandbox"
category = false
parent = "intro_groovy"
parentdescription = "Multi-package project Intro examples for Groovy."
project = "util"
description = "Utilities sub-package for Groovy Intro examples project."
version = "0.1.0"

repohost = "bitbucket.org"
repoacct = "imcomputer"
date = "2013-10-01"

readmeext = ".rst"
license = "Apache-2.0"
buildtool = "gradle"
testfrwk = "spock"

ffilib = "none"

skeletondir = "Templates/mustache/skeleton-groovy"

[_choices]
readmeext = [".rst", ".md", ".adoc"]
license = ["Apache-2.0", "MIT", "BSD-3-Clause", "GPL-3.0+", "ISC", "Unlicense",
  "Not open source"]
buildtool = ["gradle", "maven", "ant", "rake", "make"]
testfrwk = ["spock", "junit", "testng"]
executable = ["no", "yes"]
ffilib = ["none", "jna", "swig"]
